### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by KittenKicker** [dadoonet/fsriver#107]
I have ElasticSearch 1.5.0 and fsriver 1.3.1...after I install the plugin using plugin -install, when I attempt to run elasticsearch.bat i get an Initialization failed error:

NoSuchMethodError[org.elasticsearch.rest.BaseRestHandler.<init>(Lorg/elasticsearch/common/settings/Settings;Lorg/elasticsearch/client/Client;

Should I be using a different version of fsriver for this version of elastic search?

**Comment by dadoonet** [comment]
Yes. This version is not compatible with 1.5.0 (and with 1.4.x BTW)

Will be fix with #108. No ETA though.

**Comment by KittenKicker** [comment]
So the only solution right now is to go back on ES version? Or will building from source make it work with 1.5?

**Comment by dadoonet** [comment]
Rivers has just been announced as deprecated BTW: https://www.elastic.co/blog/deprecating_rivers

**Comment by dadoonet** [comment]
But yes you can fork the code and Patch it. Look at #100
